version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: todo
    container_name: todo-postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=XGumWwNXMQDAi78ajGxzBc4p
    ports:
      - "5432:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

volumes:
  todo_postgres_data:
